	./ft_string/ft_strncmp.c:int	ft_strncmp(const char *s1, const char *s2, size_t n);
	./ft_string/ft_substr.c:char	*ft_substr(char const *s, unsigned int start, size_t len);
	./ft_string/ft_striteri.c:void	ft_striteri(char *s, void (*f)(unsigned int, char *));
	./ft_string/ft_isdigit.c:int	ft_isdigit(int c);
	./ft_string/ft_putstr_fd.c:void	ft_putstr_fd(const char *s, int fd);
	./ft_string/ft_memchr.c:void	*ft_memchr(const void *s, int c, size_t n);
	./ft_string/ft_strtrim.c:static int	loc_strchr(const char *str, int c);
	./ft_string/ft_strtrim.c:static size_t	loc_strtrim_size(size_t *offset, char const *s1,;
	./ft_string/ft_strtrim.c:char	*ft_strtrim(char const *s1, char const *set);
	./ft_string/ft_islower.c:int	ft_islower(int c);
	./ft_string/ft_isalpha.c:int	ft_isalpha(int c);
	./ft_string/ft_memcmp.c:int	ft_memcmp(const void *s1, const void *s2, size_t n);
	./ft_string/ft_isupper.c:int	ft_isupper(int c);
	./ft_string/get_next_line_utils.c:int	ft_strchr_index(const char *from, char c);
	./ft_string/get_next_line_utils.c:static int	mvstr(char *str, int nb, char delim);
	./ft_string/get_next_line_utils.c:int	split_from(char **dst, char *from, int pos, char delim);
	./ft_string/ft_calloc.c:void	*ft_calloc(size_t nmemb, size_t weight);
	./ft_string/ft_atoi.c:int	ft_atoi(const char *str);
	./ft_string/ft_itoa_base.c:static int	loc_getlen(long long nbr, int blen);
	./ft_string/ft_itoa_base.c:char	*ft_itoa_base(int nbr, char *base);
	./ft_string/ft_memcpy.c:void	*ft_memcpy(void *dest, const void *src, size_t n);
	./ft_string/ft_itoa.c:static int	loc_getlen(long long nbr);
	./ft_string/ft_itoa.c:char	*ft_itoa(int nbr);
	./ft_string/ft_strndup.c:char	*ft_strndup(const char *str, size_t n);
	./ft_string/ft_tolower.c:int	ft_tolower(int c);
	./ft_string/ft_strchr.c:char	*ft_strchr(const char *str, int c);
	./ft_string/ft_toupper.c:int	ft_toupper(int c);
	./ft_string/ft_strlcat.c:size_t	ft_strlcat(char *dst, const char *src, size_t size);
	./ft_string/ft_strlcpy.c:size_t	ft_strlcpy(char *dst, const char *src, size_t size);
	./ft_string/ft_log.c:int	ft_ullogof(unsigned long long nbr, int base);
	./ft_string/ft_log.c:int	ft_llogof(long long nbr, int base);
	./ft_string/ft_log.c:int	ft_logof(int nbr, int base);
	./ft_string/ft_log.c:int	ft_log(int nbr);
	./ft_string/ft_isspace.c:int	ft_isspace(int c);
	./ft_string/ft_memmove.c:void	*ft_memmove(void *dest, const void *src, size_t n);
	./ft_string/ft_bzero.c:void	ft_bzero(void *s, size_t n);
	./ft_string/ft_putchar_fd.c:void	ft_putchar_fd(char c, int fd);
	./ft_string/ft_strdup.c:char	*ft_strdup(const char *strsrc);
	./ft_string/ft_minmax.c:int	ft_min(int a, int b);
	./ft_string/ft_minmax.c:int	ft_max(int a, int b);
	./ft_string/ft_memset.c:void	*ft_memset(void *s, int c, size_t n);
	./ft_string/get_next_line.c:char	*get_next_line(int fd);
	./ft_string/ft_strlen.c:size_t	ft_strlen(const char *str);
	./ft_string/ft_putendl_fd.c:void	ft_putendl_fd(const char *s, int fd);
	./ft_string/ft_free.c:void	ft_free(void **ptr);
	./ft_string/ft_putnbr_fd.c:void	ft_putnbr_fd(int nbr, int fd);
	./ft_string/ft_strjoin.c:char	*ft_strjoin(char const *s1, char const *s2);
	./ft_string/ft_isprint.c:int	ft_isprint(int c);
	./ft_string/ft_isalnum.c:int	ft_isalnum(int c);
	./ft_string/ft_strrchr.c:char	*ft_strrchr(const char *str, int c);
	./ft_string/ft_isascii.c:int	ft_isascii(int c);
	./ft_string/ft_split.c:static size_t	loc_get_nbwords(const char *str, char delim);
	./ft_string/ft_split.c:static char	*loc_cpy_til(const char *str, char delim, size_t *offset_str);
	./ft_string/ft_split.c:static void	loc_tbfree(void **tb);
	./ft_string/ft_split.c:char	**ft_split(const char *str, char delim);
	./ft_string/ft_utoa.c:static int	loc_getlen(unsigned long long nbr);
	./ft_string/ft_utoa.c:char	*ft_utoa(unsigned int nbr);
	./ft_string/ft_strnstr.c:char	*ft_strnstr(const char *big, const char *small, size_t n);
	./ft_string/ft_strmapi.c:char	*ft_strmapi(char const *s, char (*f)(unsigned int, char));
	./ft_vector/ft_vec_shift.c:void	ft_vec_shift(t_vector *vec, size_t start, size_t shift);
	./ft_vector/ft_vec_clear.c:void	ft_vec_clear(t_vector **vec);
	./ft_vector/ft_vec_filter.c:void	ft_vec_filter(t_vector *vec, bool (*func)(void *), void (*del)(void *));
	./ft_vector/ft_vec_cat.c:bool	ft_vec_cat(t_vector **vec_a, const t_vector *vec_b);
	./ft_vector/ft_vec_add.c:bool	ft_vec_add(t_vector **vec, void *data);
	./ft_vector/ft_vec_new.c:t_vector	*ft_vec_new(void);
	./ft_vector/ft_vec_new.c:t_vector	*ft_vec_from_size(size_t n);
	./ft_vector/ft_vec_new.c:t_vector	*ft_vec_from_array(void **data, size_t count);
	./ft_vector/ft_vec_new.c:t_vector	*ft_vec_convert_alloccarray(void **data, size_t count);
	./ft_vector/ft_vec_map.c:t_vector	*ft_vec_map(t_vector *vec, void *(*func)(void *));
	./ft_vector/ft_vec_destroy.c:bool	ft_vec_destroy(t_vector **vec);
	./ft_vector/ft_vec_apply.c:void	ft_vec_apply(t_vector *vec, void (*func)(void *));
	./ft_vector/ft_vec_reserve.c:bool	ft_vec_reserve(t_vector **vec, size_t size);
	./ft_vector/ft_vec_sort.c:static void	ft_loc_swap(void **a, void **b);
	./ft_vector/ft_vec_sort.c:void	ft_vec_sort(t_vector *vec, int (*cmp_f)(void *, void *));
	./ft_vector/ft_vec_at.c:void	*ft_vec_at(t_vector *vec, size_t n);
	./ft_config/ini/ftc_ini_pushs.c:int	ftc_ini_push_kv(const char *k, const char *v, t_inifile *file);
	./ft_config/ini/ftc_ini_pushs.c:int	ftc_ini_push_secion(const char *parent, const char *s, t_inifile *file);
	./ft_config/ini/ftc_ini_get.c:t_ini_section	*ftc_ini_get_section(const char *s, t_inifile *file);
	./ft_config/ini/ftc_ini_get.c:void	*ftc_ini_get_k(const char *k, t_inifile *file);
	./ft_config/ini/ftc_ini_inits.c:void	*ftc_ini_core_init(void);
	./ft_config/ini/ftc_ini_inits.c:void	*ftc_ini_extended_init(void);
	./ft_config/ini/ftc_ini_baseops.c:static int loc_kv_delc(const char *str, t_inifile *file);
	./ft_config/ini/ftc_ini_baseops.c:static int loc_section_delc(char *str, t_inifile *file);
	./ft_config/ini/ftc_ini_baseops.c:static int	loc_treat_str(const char *str, t_inifile *file);
	./ft_config/ini/ftc_ini_baseops.c:int	ftc_ini_load(const char *file, void *content);
	./ft_config/ini/ftc_ini_baseops.c:int	ftc_ini_save(const char *file, void *control_struct);
	./ft_config/ini/ftc_ini_baseops.c:void	*ftc_ini_get(const char *key, void *control_struct);
	./ft_config/ini/ftc_ini_baseops.c:int	ftc_ini_set(const char *key, void *value, void *control_struct);
	./ft_config/ftc_get_parser.c:t_obj_parser_type	ftc_parserby_type(t_ctype type);
	./ft_config/ftc_get_parser.c:t_obj_parser_type	ftc_parserby_suffix(const char *suffix);
	./ft_config/ftc_baseop.c:t_config	*ft_init_config(const char *filepath, t_ctype config_type);
	./ft_config/ftc_baseop.c:int	ft_congig_load(t_config *config);
	./ft_config/ftc_baseop.c:int	ft_congig_save(t_config *config);
	./ft_config/ftc_baseop.c:void	*ft_congig_get(t_config *config);
	./ft_config/ftc_baseop.c:int	ft_congig_set(t_config *config, const char *key, void *value);
	./ft_list/ft_list_ll_rev.c:t_list	*ft_listrev(t_list **head);
	./ft_list/ft_list_ll_clear.c:void	ft_listclear(t_list **lst, t_data_apply del);
	./ft_list/ft_list_ll_new.c:t_list	*ft_listnew(const void *content);
	./ft_list/ft_list_dl_subrange.c:t_dlist	*ft_list_dl_subrange(t_dlist *src, t_dlist *to);
	./ft_list/ft_list_dl_subrange.c:t_dlist	*ft_list_dl_subrange_to(t_dlist *head, t_dlist *end);
	./ft_list/ft_list_ll_add_back.c:void	ft_listadd_back(t_list **lst, t_list *new);
	./ft_list/ft_list_dl_delete.c:int	ft_list_dl_delete_self(t_dlist *node);
	./ft_list/ft_list_dl_delete.c:size_t	ft_list_dl_delete_range(t_dlist *start, t_dlist *target);
	./ft_list/ft_list_dl_delete.c:size_t	ft_list_dl_delete(t_dlist **head);
	./ft_list/ft_list_dl_delete.c:size_t	ft_list_dl_delete_dup(t_dlist **src);
	./ft_list/ft_list_dl_create.c:t_dlist	*ft_list_dl(void);
	./ft_list/ft_list_dl_create.c:t_dlist	*ft_list_dl_create(void *const data);
	./ft_list/ft_list_dl_create.c:t_dlist	*ft_list_dl_copy(const t_dlist *const other);
	./ft_list/ft_list_dl_create.c:t_dlist	*ft_list_dl_copy_list(const t_dlist *const other);
	./ft_list/ft_list_dl_iterator.c:t_dlist	*ft_list_dl_at(t_dlist *head, size_t index);
	./ft_list/ft_list_dl_iterator.c:t_dlist	*ft_list_dl_end(t_dlist *head);
	./ft_list/ft_list_dl_iterator.c:t_dlist	*ft_list_dl_begin(const t_dlist *head);
	./ft_list/ft_list_dl_iterator.c:size_t	ft_list_dl_count(const t_dlist *head);
	./ft_list/ft_list_ll_last.c:t_list	*ft_listlast(t_list *lst);
	./ft_list/ft_list_dl_manip.c:t_dlist	*ft_list_dl_push(t_dlist **node, t_dlist *added);
	./ft_list/ft_list_dl_manip.c:t_dlist	*ft_list_dl_push_back(t_dlist **node, t_dlist *added);
	./ft_list/ft_list_dl_manip.c:void	*ft_list_dl_pop(t_dlist **node);
	./ft_list/ft_list_dl_manip.c:void	*ft_list_dl_pop_back(t_dlist **node);
	./ft_list/ft_list_ll_add_front.c:void	ft_listadd_front(t_list **lst, t_list *new);
	./ft_list/ft_list_dl_get.c:void	**ft_list_dl_get_datas(const t_dlist *src);
	./ft_list/ft_list_dl_get.c:t_dlist	**ft_list_dl_get_nodes(const t_dlist *src);
	./ft_list/ft_list_dl_clear.c:size_t	ft_list_dl_clear(t_dlist *head);
	./ft_list/ft_list_dl_clear.c:size_t	ft_list_dl_clear_range(t_dlist *start, t_dlist *end);
	./ft_list/ft_list_ll_delone.c:void	ft_listdelone(t_list *lst, t_data_apply del);
	./ft_list/ft_list_dl_apply.c:size_t	ft_list_dl_apply(t_dlist *start, t_data_apply applied);
	./ft_list/ft_list_dl_apply.c:size_t	ft_list_dl_apply_range(t_dlist *start, const t_dlist *end,;
	./ft_list/ft_list_dl_apply.c:size_t	ft_list_dl_apply_range_node(t_dlist *start, const t_dlist *end,;
	./ft_list/ft_list_ll_map.c:t_list	*ft_listmap(t_list *lst, void *(*f)(void *), t_data_apply del);
	./ft_list/ft_list_ll_iter.c:void	ft_listiter(t_list *lst, t_data_apply f);
	./ft_list/ft_list_dl_size.c:size_t	ft_list_dl_size(t_dlist *head);
	./ft_list/ft_list_dl_size.c:size_t	ft_list_dl_size_of_data(t_dlist *head, t_data_is function);
	./ft_list/ft_list_ll_size.c:int	ft_listsize(t_list *lst);
